
export const FETCH_POLLS = 'FETCH_POLLS'
export const RECEIVE_POLLS = 'RECEIVE_POLLS'
export const CREATE_POLL = 'CREATE_POLL'

export const FETCH_RESPONSES = 'FETCH_RESPONSES'
export const RECEIVE_RESPONSES = 'RECEIVE_RESPONSES'

export const FETCH_USERS = 'FETCH_USERS'
export const RECEIVE_USERS = 'RECEIVE_USERS'
